from obspy import read_inventory
from obspy.core.inventory.util import Site
import sys

def patch_stationxml(infile, outfile):
    inv = read_inventory(infile)
    count = 0

    for net in inv:
        for sta in net:
            if not sta.site:
                sta.site = Site(name=f"{sta.code}_SITE", description=f"Autogenerated site description for {sta.code}")
                count += 1
            else:
                if not sta.site.name:
                    sta.site.name = f"{sta.code}_SITE"
                    count += 1
                if not sta.site.description:
                    sta.site.description = f"Autogenerated site description for {sta.code}"
                    count += 1

    inv.write(outfile, format="STATIONXML")
    print(f"[OK] Patched {count} fields. Output written to: {outfile}")

if __name__ == "__main__":
    infile = sys.argv[1]
    outfile = sys.argv[2] if len(sys.argv) > 2 else "patched_stationxml.xml"
    patch_stationxml(infile, outfile)
